### ISSUE TITLE
Tracking parity with other test runner functionality

### ISSUE THREAD

**Issue by mcataford** [mcataford/works-on-my-machine#2]
This tracker catalogues functionality that should be supported.

_The list will be built out incrementally, contributions welcome!_

# Test case definition

- [ ] `describe` to organize test groups
- [x] `test` to define individual tests (#1)
- [x] `it` as an alias to `test` (#1)
- [ ] parametrization with `each` (list)

# Asserting

- [x] `expect` support (basic) (#1)
- [x] `toEqual` support for basic types (#1)
- [x] `toBe` support for basic types (#1)
- [ ] `not` to invert any matcher
- [ ] `toThrow` to assert on thrown exceptions

**Comment by mcataford** [comment]
Getting closer and closer to supporting all items needed by [@mcataford/packwatch](https://github.com/mcataford/packwatch). :tada:
